# Generated by Django 4.2.3 on 2023-11-05 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_story_category_alter_story_author_alter_story_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='assigned_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='reading_list',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
