# Generated by Django 4.2.3 on 2023-11-05 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_readinglist_assigned_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='reading_list',
            field=models.CharField(blank=True, default='{}', max_length=1000),
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
