# Generated by Django 4.2.3 on 2023-11-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_readinglist_reading_list_alter_story_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='reading_list',
            field=models.CharField(blank=True, default='{"reading_list":[]}', max_length=1000),
        ),
    ]
