# Generated by Django 4.2.3 on 2023-11-05 17:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_readinglist_reading_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
