# Generated by Django 4.2.3 on 2023-11-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_story_content_alter_story_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='state',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Awaiting Approval', 'Awaiting Approval'), ('Published', 'Published')], default='Draft', max_length=20, null=True),
        ),
    ]
