# Generated by Django 4.2.3 on 2023-11-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_story_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='state',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Awaiting Approval', 'Awaiting Approval'), ('Published', 'Published'), ('Deleted', 'Deleted')], default='Draft', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='New Story', max_length=200),
        ),
    ]
