# Generated by Django 3.2.2 on 2023-11-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_story_date_alter_story_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Headline Image'),
        ),
        migrations.AlterField(
            model_name='story',
            name='state',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Awaiting Editor Approval', 'Awaiting Editor Approval'), ('Awaiting Editor In Chief Approval', 'Awaiting Editor In Chief Approval'), ('Published', 'Published'), ('Deleted', 'Deleted')], default='Draft', max_length=50, null=True),
        ),
    ]
